create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null unique,
  category text not null default 'Bovina',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.break_reports (
  id bigint generated by default as identity primary key,
  date date not null,
  requisition text not null default '',
  employee text not null,
  total_kg numeric(12,3) not null default 0,
  total_cost numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.break_items (
  id bigint generated by default as identity primary key,
  report_id bigint not null references public.break_reports(id) on delete cascade,
  product_id bigint references public.products(id),
  product_name text not null,
  quantity_kg numeric(12,3) not null check (quantity_kg > 0),
  cost numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.time_offs (
  id bigint generated by default as identity primary key,
  employee text not null,
  date date not null,
  type text not null default 'Semanal',
  status text not null default 'Solicitada'
    check (status in ('Solicitada', 'Confirmada', 'Realizada')),
  coverage text not null default '',
  notes text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.user_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role text not null,
  store text not null default 'Fort Atacadista • Barreiros',
  username text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.break_reports enable row level security;
alter table public.break_items enable row level security;
alter table public.time_offs enable row level security;
alter table public.user_profiles enable row level security;

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.products to authenticated;
grant select, insert, update, delete on public.break_reports to authenticated;
grant select, insert, update, delete on public.break_items to authenticated;
grant select, insert, update, delete on public.time_offs to authenticated;
grant select, insert, update on public.user_profiles to authenticated;
grant usage, select on all sequences in schema public to authenticated;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'products', 'break_reports', 'break_items', 'time_offs', 'user_profiles'
  ]
  loop
    execute format('drop policy if exists "Authenticated users manage data" on public.%I', table_name);
    execute format(
      'create policy "Authenticated users manage data" on public.%I for all to authenticated using (true) with check (true)',
      table_name
    );
  end loop;
end $$;

insert into public.products (name, category) values
  ('ACÉM BOVINO COM OSSO', 'Bovina'),
  ('CHULETA BOVINA', 'Bovina'),
  ('COSTELA BOVINA', 'Bovina'),
  ('FILÉ DUPLO BOVINO FATIADO - BANDEJA', 'Bovina'),
  ('LAGARTO BOVINO FRESCO BIFE FAMÍLIA - BANDEJA', 'Bovina'),
  ('OSSO BUCO BOVINO CARNE FRESCA - BANDEJA', 'Bovina'),
  ('PALETA BOVINA COM OSSO', 'Bovina'),
  ('PEITO BOVINO COM OSSO', 'Bovina')
on conflict (name) do nothing;

do $$
declare
  report bigint;
begin
  select id into report
  from public.break_reports
  where requisition = '28076039'
  limit 1;

  if report is null then
    insert into public.break_reports (
      date, requisition, employee, total_kg, total_cost
    ) values (
      '2026-06-25', '28076039', 'Vanusa Alves de Oliveira', 19.966, 640.57
    ) returning id into report;

    insert into public.break_items (
      report_id, product_id, product_name, quantity_kg, cost
    )
    select report, p.id, seed.name, seed.quantity_kg, seed.cost
    from (
      values
        ('ACÉM BOVINO COM OSSO', 1.800::numeric, 46.55::numeric),
        ('CHULETA BOVINA', 2.600::numeric, 81.48::numeric),
        ('COSTELA BOVINA', 2.090::numeric, 49.55::numeric),
        ('FILÉ DUPLO BOVINO FATIADO - BANDEJA', 4.800::numeric, 235.44::numeric),
        ('LAGARTO BOVINO FRESCO BIFE FAMÍLIA - BANDEJA', 0.478::numeric, 17.74::numeric),
        ('OSSO BUCO BOVINO CARNE FRESCA - BANDEJA', 1.600::numeric, 39.16::numeric),
        ('PALETA BOVINA COM OSSO', 0.398::numeric, 10.29::numeric),
        ('PEITO BOVINO COM OSSO', 6.200::numeric, 160.36::numeric)
    ) as seed(name, quantity_kg, cost)
    join public.products p on p.name = seed.name;
  end if;
end $$;

insert into public.time_offs (employee, date, type, status, coverage, notes)
select seed.*
from (
  values
    ('Carlos Mendes', '2026-07-27'::date, 'Semanal', 'Confirmada', 'Rafael Souza', 'Folga de segunda-feira'),
    ('Juliana Ferreira', '2026-07-28'::date, 'Compensatória', 'Confirmada', 'Patrícia Lima', 'Cobertura confirmada'),
    ('Rafael Souza', '2026-07-30'::date, 'Semanal', 'Solicitada', 'Carlos Mendes', ''),
    ('Patrícia Lima', '2026-08-01'::date, 'Semanal', 'Confirmada', 'Juliana Ferreira', '')
) as seed(employee, date, type, status, coverage, notes)
where not exists (
  select 1 from public.time_offs t
  where t.employee = seed.employee and t.date = seed.date
);

insert into public.user_profiles (id, full_name, role, store, username)
select
  id,
  'Vanusa Alves de Oliveira',
  'Encarregada do açougue',
  'Fort Atacadista • Barreiros',
  'vanusa.alves'
from auth.users
where email = 'vanusa.alves@cortecerto.app'
on conflict (id) do update set
  full_name = excluded.full_name,
  role = excluded.role,
  store = excluded.store,
  username = excluded.username,
  active = true;
