create table if not exists public.products (
  id bigint generated by default as identity primary key,
  code text,
  name text not null unique,
  category text not null default 'Bovina',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.break_reports (
  id bigint generated by default as identity primary key,
  date date not null,
  requisition text not null default '',
  employee text not null,
  total_kg numeric(12,3) not null default 0,
  total_cost numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.break_items (
  id bigint generated by default as identity primary key,
  report_id bigint not null references public.break_reports(id) on delete cascade,
  product_id bigint references public.products(id),
  product_code text not null default '',
  product_name text not null,
  quantity_kg numeric(12,3) not null check (quantity_kg > 0),
  cost numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

alter table public.products add column if not exists code text;
alter table public.break_items add column if not exists product_code text not null default '';
create unique index if not exists products_code_unique
  on public.products (code)
  where code is not null and code <> '';

create table if not exists public.time_offs (
  id bigint generated by default as identity primary key,
  employee text not null,
  date date not null,
  type text not null default 'Semanal',
  status text not null default 'Solicitada'
    check (status in ('Solicitada', 'Confirmada', 'Realizada')),
  coverage text not null default '',
  notes text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.user_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role text not null,
  store text not null default 'Fort Atacadista • Barreiros',
  username text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.break_reports enable row level security;
alter table public.break_items enable row level security;
alter table public.time_offs enable row level security;
alter table public.user_profiles enable row level security;

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.products to authenticated;
grant select, insert, update, delete on public.break_reports to authenticated;
grant select, insert, update, delete on public.break_items to authenticated;
grant select, insert, update, delete on public.time_offs to authenticated;
grant select, insert, update on public.user_profiles to authenticated;
grant usage, select on all sequences in schema public to authenticated;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'products', 'break_reports', 'break_items', 'time_offs', 'user_profiles'
  ]
  loop
    execute format('drop policy if exists "Authenticated users manage data" on public.%I', table_name);
    execute format(
      'create policy "Authenticated users manage data" on public.%I for all to authenticated using (true) with check (true)',
      table_name
    );
  end loop;
end $$;

update public.products set code = '727598', name = 'ACEM BOV.KG C/OSSO' where name = 'ACÉM BOVINO COM OSSO';
update public.products set code = '745510', name = 'CHULETA BOV KG' where name = 'CHULETA BOVINA';
update public.products set code = '945510', name = 'COSTELA BOV.KG' where name = 'COSTELA BOVINA';
update public.products set code = '778957', name = 'FILE DUPLO BOV.KG FAT. BANDEJA' where name = 'FILÉ DUPLO BOVINO FATIADO - BANDEJA';
update public.products set code = '841706', name = 'LAGARTO BOV.KG FRESCA BIFE FAM. BAND.' where name = 'LAGARTO BOVINO FRESCO BIFE FAMÍLIA - BANDEJA';
update public.products set code = '1535471', name = 'OSSO BUCO BOV.KG CARNE FRESCA BDJ' where name = 'OSSO BUCO BOVINO CARNE FRESCA - BANDEJA';
update public.products set code = '841099', name = 'PALETA BOV.KG C OSSO' where name = 'PALETA BOVINA COM OSSO';
update public.products set code = '743679', name = 'PEITO BOV.KG C OSSO' where name = 'PEITO BOVINO COM OSSO';

insert into public.products (code, name, category) values
  ('727598', 'ACEM BOV.KG C/OSSO', 'Bovina'),
  ('945510', 'COSTELA BOV.KG', 'Bovina'),
  ('719501', 'COXAO MOLE BOV.KG BIFE FAMILIAR', 'Bovina'),
  ('1366998', 'FRALDINHA BOV.KG CARNE FRESCA ATEND', 'Bovina'),
  ('743679', 'PEITO BOV.KG C OSSO', 'Bovina'),
  ('717282', 'ALCATRA BOV.KG PEDACO', 'Bovina'),
  ('760579', 'BIFE COXAO DURO ECONOMICO KG', 'Bovina'),
  ('2308525', 'CARNE MOIDA BOV.KG PRIMEIRA ESPEC.', 'Bovina'),
  ('778800', 'COXAO DURO BOV.KG BIFE', 'Bovina'),
  ('778729', 'COXAO DURO BOV.KG PEDACO', 'Bovina'),
  ('744891', 'FILE MIGNON BOV.KG PECA', 'Bovina'),
  ('841099', 'PALETA BOV.KG C OSSO', 'Bovina'),
  ('546031', 'PONTA PEITO BOV.KG FRESCA BD.FAM', 'Bovina'),
  ('745901', 'ALCATRA BOV.KG C/OSSO FAT.', 'Bovina'),
  ('1535471', 'OSSO BUCO BOV.KG CARNE FRESCA BDJ', 'Bovina'),
  ('952831', 'BISTECA BOV.KG', 'Bovina'),
  ('745812', 'BISTECA SUINA KG FAT.BAND', 'Suína'),
  ('1327110', 'CARNE SUINA KG C/OSSO TOUCINHO', 'Suína'),
  ('778957', 'FILE DUPLO BOV.KG FAT. BANDEJA', 'Bovina'),
  ('745510', 'CHULETA BOV KG', 'Bovina'),
  ('841706', 'LAGARTO BOV.KG FRESCA BIFE FAM. BAND.', 'Bovina'),
  ('1647423', 'MAMINHA BOV.KG INT.P CHURRASCO C.FRESCA', 'Bovina')
on conflict (name) do update set
  code = excluded.code,
  category = excluded.category,
  active = true;

update public.break_items item
set product_code = product.code
from public.products product
where item.product_id = product.id
  and coalesce(item.product_code, '') = ''
  and coalesce(product.code, '') <> '';

do $$
declare
  report bigint;
begin
  select id into report
  from public.break_reports
  where requisition = '28076039'
  limit 1;

  if report is null then
    insert into public.break_reports (
      date, requisition, employee, total_kg, total_cost
    ) values (
      '2026-06-25', '28076039', 'Vanusa Alves de Oliveira', 19.966, 640.57
    ) returning id into report;

    insert into public.break_items (
      report_id, product_id, product_code, product_name, quantity_kg, cost
    )
    select report, p.id, seed.code, seed.name, seed.quantity_kg, seed.cost
    from (
      values
        ('727598', 'ACEM BOV.KG C/OSSO', 1.800::numeric, 46.55::numeric),
        ('745510', 'CHULETA BOV KG', 2.600::numeric, 81.48::numeric),
        ('945510', 'COSTELA BOV.KG', 2.090::numeric, 49.55::numeric),
        ('778957', 'FILE DUPLO BOV.KG FAT. BANDEJA', 4.800::numeric, 235.44::numeric),
        ('841706', 'LAGARTO BOV.KG FRESCA BIFE FAM. BAND.', 0.478::numeric, 17.74::numeric),
        ('1535471', 'OSSO BUCO BOV.KG CARNE FRESCA BDJ', 1.600::numeric, 39.16::numeric),
        ('841099', 'PALETA BOV.KG C OSSO', 0.398::numeric, 10.29::numeric),
        ('743679', 'PEITO BOV.KG C OSSO', 6.200::numeric, 160.36::numeric)
    ) as seed(code, name, quantity_kg, cost)
    join public.products p on p.code = seed.code;
  end if;
end $$;

do $$
declare
  report bigint;
begin
  select id into report from public.break_reports where requisition = '28113585' limit 1;
  if report is null then
    insert into public.break_reports (date, requisition, employee, total_kg, total_cost)
    values ('2026-07-03', '28113585', 'Fernanda Almeida Gomes de Oliveira', 19.158, 631.78)
    returning id into report;

    insert into public.break_items (report_id, product_id, product_code, product_name, quantity_kg, cost)
    select report, p.id, seed.code, p.name, seed.quantity_kg, seed.cost
    from (values
      ('727598', 2.200::numeric, 56.92::numeric),
      ('945510', 7.800::numeric, 165.25::numeric),
      ('719501', 5.000::numeric, 214.33::numeric),
      ('1366998', 3.603::numeric, 180.92::numeric),
      ('743679', 0.555::numeric, 14.36::numeric)
    ) as seed(code, quantity_kg, cost)
    join public.products p on p.code = seed.code;
  end if;

  report := null;
  select id into report from public.break_reports where requisition = '28123378' limit 1;
  if report is null then
    insert into public.break_reports (date, requisition, employee, total_kg, total_cost)
    values ('2026-07-06', '28123378', 'Marcineia Magno Perdigao', 22.224, 800.75)
    returning id into report;

    insert into public.break_items (report_id, product_id, product_code, product_name, quantity_kg, cost)
    select report, p.id, seed.code, p.name, seed.quantity_kg, seed.cost
    from (values
      ('727598', 0.526::numeric, 13.61::numeric),
      ('745901', 1.170::numeric, 53.80::numeric),
      ('2308525', 11.000::numeric, 432.82::numeric),
      ('1366998', 2.000::numeric, 100.43::numeric),
      ('1535471', 0.528::numeric, 12.93::numeric),
      ('743679', 5.800::numeric, 150.06::numeric),
      ('546031', 1.200::numeric, 37.11::numeric)
    ) as seed(code, quantity_kg, cost)
    join public.products p on p.code = seed.code;
  end if;

  report := null;
  select id into report from public.break_reports where requisition = '28162809' limit 1;
  if report is null then
    insert into public.break_reports (date, requisition, employee, total_kg, total_cost)
    values ('2026-07-14', '28162809', 'Marcineia Magno Perdigao', 15.294, 443.94)
    returning id into report;

    insert into public.break_items (report_id, product_id, product_code, product_name, quantity_kg, cost)
    select report, p.id, seed.code, p.name, seed.quantity_kg, seed.cost
    from (values
      ('727598', 0.405::numeric, 10.46::numeric),
      ('745901', 0.582::numeric, 26.76::numeric),
      ('2308525', 1.200::numeric, 46.56::numeric),
      ('745510', 2.800::numeric, 84.87::numeric),
      ('945510', 7.400::numeric, 175.45::numeric),
      ('841706', 0.822::numeric, 30.37::numeric),
      ('1647423', 0.545::numeric, 27.81::numeric),
      ('1535471', 0.454::numeric, 11.10::numeric),
      ('743679', 0.596::numeric, 15.39::numeric),
      ('546031', 0.490::numeric, 15.16::numeric)
    ) as seed(code, quantity_kg, cost)
    join public.products p on p.code = seed.code;
  end if;

  report := null;
  select id into report from public.break_reports where requisition = '28170757' limit 1;
  if report is null then
    insert into public.break_reports (date, requisition, employee, total_kg, total_cost)
    values ('2026-07-16', '28170757', 'Iago Lohan Aires Saraiva', 34.447, 1646.56)
    returning id into report;

    insert into public.break_items (report_id, product_id, product_code, product_name, quantity_kg, cost)
    select report, p.id, seed.code, p.name, seed.quantity_kg, seed.cost
    from (values
      ('717282', 4.913::numeric, 254.76::numeric),
      ('760579', 4.800::numeric, 183.52::numeric),
      ('2308525', 5.000::numeric, 196.14::numeric),
      ('778800', 2.782::numeric, 106.37::numeric),
      ('778729', 3.179::numeric, 117.04::numeric),
      ('744891', 7.529::numeric, 601.82::numeric),
      ('841099', 1.244::numeric, 32.17::numeric),
      ('546031', 5.000::numeric, 154.74::numeric)
    ) as seed(code, quantity_kg, cost)
    join public.products p on p.code = seed.code;
  end if;

  report := null;
  select id into report from public.break_reports where requisition = '28182183' limit 1;
  if report is null then
    insert into public.break_reports (date, requisition, employee, total_kg, total_cost)
    values ('2026-07-18', '28182183', 'Fernanda Almeida Gomes de Oliveira', 21.184, 559.22)
    returning id into report;

    insert into public.break_items (report_id, product_id, product_code, product_name, quantity_kg, cost)
    select report, p.id, seed.code, p.name, seed.quantity_kg, seed.cost
    from (values
      ('952831', 4.200::numeric, 140.91::numeric),
      ('745812', 1.184::numeric, 12.16::numeric),
      ('945510', 11.200::numeric, 264.89::numeric),
      ('778800', 1.800::numeric, 68.82::numeric),
      ('743679', 2.800::numeric, 72.43::numeric)
    ) as seed(code, quantity_kg, cost)
    join public.products p on p.code = seed.code;
  end if;

  report := null;
  select id into report from public.break_reports where requisition = '28186010' limit 1;
  if report is null then
    insert into public.break_reports (date, requisition, employee, total_kg, total_cost)
    values ('2026-07-20', '28186010', 'Marcineia Magno Perdigao', 7.300, 216.00)
    returning id into report;

    insert into public.break_items (report_id, product_id, product_code, product_name, quantity_kg, cost)
    select report, p.id, seed.code, p.name, seed.quantity_kg, seed.cost
    from (values
      ('952831', 2.000::numeric, 67.19::numeric),
      ('1327110', 1.300::numeric, 12.65::numeric),
      ('945510', 2.400::numeric, 59.70::numeric),
      ('778957', 1.600::numeric, 76.46::numeric)
    ) as seed(code, quantity_kg, cost)
    join public.products p on p.code = seed.code;
  end if;
end $$;

delete from public.time_offs
where employee in ('Carlos Mendes', 'Juliana Ferreira', 'Rafael Souza', 'Patrícia Lima');

insert into public.time_offs (employee, date, type, status, coverage, notes)
select seed.*
from (
  values
    ('Anderson Ruan do Nascimento', '2026-07-23'::date, 'Semanal', 'Confirmada', '', 'Turno: Abertura'),
    ('Anderson Ruan do Nascimento', '2026-07-30'::date, 'Semanal', 'Confirmada', '', 'Turno: Abertura'),
    ('Anderson Ruan do Nascimento', '2026-08-02'::date, 'Domingo', 'Confirmada', '', 'Turno: Abertura'),
    ('Anderson Ruan do Nascimento', '2026-08-06'::date, 'Semanal', 'Confirmada', '', 'Turno: Abertura'),
    ('Anderson Ruan do Nascimento', '2026-08-13'::date, 'Semanal', 'Confirmada', '', 'Turno: Abertura'),
    ('Anderson Ruan do Nascimento', '2026-08-16'::date, 'Domingo', 'Confirmada', '', 'Turno: Abertura'),

    ('Filipe dos Santos Vieira', '2026-07-20'::date, 'Semanal', 'Confirmada', '', 'Turno: Abertura'),
    ('Filipe dos Santos Vieira', '2026-07-26'::date, 'Domingo', 'Confirmada', '', 'Turno: Abertura'),
    ('Filipe dos Santos Vieira', '2026-07-27'::date, 'Semanal', 'Confirmada', '', 'Turno: Abertura'),
    ('Filipe dos Santos Vieira', '2026-08-03'::date, 'Semanal', 'Confirmada', '', 'Turno: Abertura'),
    ('Filipe dos Santos Vieira', '2026-08-09'::date, 'Domingo', 'Confirmada', '', 'Turno: Abertura'),
    ('Filipe dos Santos Vieira', '2026-08-10'::date, 'Semanal', 'Confirmada', '', 'Turno: Abertura'),
    ('Filipe dos Santos Vieira', '2026-08-17'::date, 'Semanal', 'Confirmada', '', 'Turno: Abertura'),

    ('Vanusa Alves de Oliveira', '2026-07-22'::date, 'Semanal', 'Confirmada', '', 'Turno: Abertura'),
    ('Vanusa Alves de Oliveira', '2026-07-26'::date, 'Domingo', 'Confirmada', '', 'Turno: Abertura'),
    ('Vanusa Alves de Oliveira', '2026-07-29'::date, 'Semanal', 'Confirmada', '', 'Turno: Abertura'),
    ('Vanusa Alves de Oliveira', '2026-08-05'::date, 'Semanal', 'Confirmada', '', 'Turno: Abertura'),
    ('Vanusa Alves de Oliveira', '2026-08-09'::date, 'Domingo', 'Confirmada', '', 'Turno: Abertura'),
    ('Vanusa Alves de Oliveira', '2026-08-12'::date, 'Semanal', 'Confirmada', '', 'Turno: Abertura'),
    ('Vanusa Alves de Oliveira', '2026-08-19'::date, 'Semanal', 'Confirmada', '', 'Turno: Abertura'),

    ('Diego Andrade Amaral', '2026-07-21'::date, 'Semanal', 'Confirmada', '', 'Turno: Fechamento'),
    ('Diego Andrade Amaral', '2026-07-28'::date, 'Semanal', 'Confirmada', '', 'Turno: Fechamento'),
    ('Diego Andrade Amaral', '2026-08-02'::date, 'Domingo', 'Confirmada', '', 'Turno: Fechamento'),
    ('Diego Andrade Amaral', '2026-08-04'::date, 'Semanal', 'Confirmada', '', 'Turno: Fechamento'),
    ('Diego Andrade Amaral', '2026-08-11'::date, 'Semanal', 'Confirmada', '', 'Turno: Fechamento'),
    ('Diego Andrade Amaral', '2026-08-16'::date, 'Domingo', 'Confirmada', '', 'Turno: Fechamento'),
    ('Diego Andrade Amaral', '2026-08-18'::date, 'Semanal', 'Confirmada', '', 'Turno: Fechamento'),

    ('Dionne Willy', '2026-07-20'::date, 'Semanal', 'Confirmada', '', 'Turno: Fechamento'),
    ('Dionne Willy', '2026-07-27'::date, 'Semanal', 'Confirmada', '', 'Turno: Fechamento'),
    ('Dionne Willy', '2026-08-02'::date, 'Domingo', 'Confirmada', '', 'Turno: Fechamento'),
    ('Dionne Willy', '2026-08-03'::date, 'Semanal', 'Confirmada', '', 'Turno: Fechamento'),
    ('Dionne Willy', '2026-08-10'::date, 'Semanal', 'Confirmada', '', 'Turno: Fechamento'),
    ('Dionne Willy', '2026-08-16'::date, 'Domingo', 'Confirmada', '', 'Turno: Fechamento'),
    ('Dionne Willy', '2026-08-17'::date, 'Semanal', 'Confirmada', '', 'Turno: Fechamento'),

    ('Alessandra Veiga', '2026-07-21'::date, 'Semanal', 'Confirmada', '', 'Turno: Intermediário'),
    ('Alessandra Veiga', '2026-07-28'::date, 'Semanal', 'Confirmada', '', 'Turno: Intermediário'),
    ('Alessandra Veiga', '2026-08-02'::date, 'Domingo', 'Confirmada', '', 'Turno: Intermediário'),
    ('Alessandra Veiga', '2026-08-04'::date, 'Semanal', 'Confirmada', '', 'Turno: Intermediário'),
    ('Alessandra Veiga', '2026-08-11'::date, 'Semanal', 'Confirmada', '', 'Turno: Intermediário'),
    ('Alessandra Veiga', '2026-08-16'::date, 'Domingo', 'Confirmada', '', 'Turno: Intermediário'),
    ('Alessandra Veiga', '2026-08-18'::date, 'Semanal', 'Confirmada', '', 'Turno: Intermediário'),

    ('Douglas Galdino Moreira', '2026-07-22'::date, 'Semanal', 'Confirmada', '', 'Turno: Fechamento'),
    ('Douglas Galdino Moreira', '2026-07-26'::date, 'Domingo', 'Confirmada', '', 'Turno: Fechamento'),
    ('Douglas Galdino Moreira', '2026-07-29'::date, 'Semanal', 'Confirmada', '', 'Turno: Fechamento'),
    ('Douglas Galdino Moreira', '2026-08-05'::date, 'Semanal', 'Confirmada', '', 'Turno: Fechamento'),
    ('Douglas Galdino Moreira', '2026-08-09'::date, 'Domingo', 'Confirmada', '', 'Turno: Fechamento'),
    ('Douglas Galdino Moreira', '2026-08-12'::date, 'Semanal', 'Confirmada', '', 'Turno: Fechamento'),
    ('Douglas Galdino Moreira', '2026-08-19'::date, 'Semanal', 'Confirmada', '', 'Turno: Fechamento'),

    ('Carlos J. Velasquez', '2026-07-20'::date, 'Semanal', 'Confirmada', '', 'Turno: Fechamento'),
    ('Carlos J. Velasquez', '2026-07-27'::date, 'Semanal', 'Confirmada', '', 'Turno: Fechamento'),
    ('Carlos J. Velasquez', '2026-08-02'::date, 'Domingo', 'Confirmada', '', 'Turno: Fechamento'),
    ('Carlos J. Velasquez', '2026-08-03'::date, 'Semanal', 'Confirmada', '', 'Turno: Fechamento'),
    ('Carlos J. Velasquez', '2026-08-10'::date, 'Semanal', 'Confirmada', '', 'Turno: Fechamento'),
    ('Carlos J. Velasquez', '2026-08-16'::date, 'Domingo', 'Confirmada', '', 'Turno: Fechamento'),
    ('Carlos J. Velasquez', '2026-08-17'::date, 'Semanal', 'Confirmada', '', 'Turno: Fechamento'),

    ('Eduardo Barrios Rodriguez', '2026-07-23'::date, 'Semanal', 'Confirmada', '', 'Turno: Abertura'),
    ('Eduardo Barrios Rodriguez', '2026-07-30'::date, 'Semanal', 'Confirmada', '', 'Turno: Abertura'),
    ('Eduardo Barrios Rodriguez', '2026-08-02'::date, 'Domingo', 'Confirmada', '', 'Turno: Abertura'),
    ('Eduardo Barrios Rodriguez', '2026-08-06'::date, 'Semanal', 'Confirmada', '', 'Turno: Abertura'),
    ('Eduardo Barrios Rodriguez', '2026-08-13'::date, 'Semanal', 'Confirmada', '', 'Turno: Abertura'),
    ('Eduardo Barrios Rodriguez', '2026-08-16'::date, 'Domingo', 'Confirmada', '', 'Turno: Abertura')
) as seed(employee, date, type, status, coverage, notes)
where not exists (
  select 1 from public.time_offs t
  where t.employee = seed.employee and t.date = seed.date
);

insert into public.user_profiles (id, full_name, role, store, username)
select
  id,
  'Vanusa Alves de Oliveira',
  'Encarregada do açougue',
  'Fort Atacadista • Barreiros',
  'vanusa.alves'
from auth.users
where email = 'vanusa.alves@cortecerto.app'
on conflict (id) do update set
  full_name = excluded.full_name,
  role = excluded.role,
  store = excluded.store,
  username = excluded.username,
  active = true;
